
target ‘NewProject’ do

pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'JSONKit-NoWarning',    '1.2'
pod 'SDWebImage', '~> 4.0.0'

#cash
pod 'AutoCoding', '~> 2.2.2'

end



